# Generated by Django 4.1.2 on 2022-10-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Hostels name')),
                ('checkindate', models.DateField(verbose_name='cin')),
                ('checkoutdate', models.DateField(verbose_name='cout')),
                ('address', models.CharField(max_length=300)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('descriptions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('phone_no', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.DeleteModel(
            name='booking_info',
        ),
        migrations.AddField(
            model_name='hostels',
            name='customers',
            field=models.ManyToManyField(blank=True, to='IA.reservations'),
        ),
    ]
