# Generated by Django 4.1.2 on 2022-10-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0002_hostels_reservations_delete_booking_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='checkindate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='checkoutdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
