# Generated by Django 4.1.2 on 2022-11-21 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0004_admin_hostels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='adults',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='children',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)]),
        ),
    ]
