# Generated by Django 4.1.2 on 2022-12-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0005_alter_hostels_adults_alter_hostels_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
