# Generated by Django 4.1.2 on 2022-12-08 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0006_hostels_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='children',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
