# Generated by Django 4.1.2 on 2022-12-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0007_alter_hostels_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('guide', models.BooleanField(blank=True)),
                ('guide_tours', models.BooleanField(blank=True)),
                ('car_rental', models.BooleanField(blank=True)),
            ],
        ),
    ]
