# Generated by Django 4.1.2 on 2023-02-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0008_ondemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='hostels',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservations',
            name='checkindate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='checkoutdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IA.hostels'),
        ),
    ]
