# Generated by Django 4.1.2 on 2023-02-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0011_alter_hostels_price_per_night_alter_hostels_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostels',
            old_name='rating',
            new_name='ratings',
        ),
    ]
