git # Generated by Django 4.1.2 on 2023-03-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0013_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
